### ISSUE TITLE
Bretton Woods image map

### ISSUE THREAD

**Issue by JasonD94** [JasonD94/Dynamic-Ski-Maps#13]
Create an image map for the Bretton Woods page.

Use [this image](http://downing.io/Ski-Maps/img/maps_imgs/bretton_woods.jpg) in GIMP.
[Tutorial on Image Maps.](https://docs.gimp.org/en/plug-in-imagemap.html)

You may want to crop the image before making the map. I suggest removing the useless parking lot / forest around the map, and cutting out the clouds / distant mountains on the top.

**Comment by BrendanBousquet** [comment]
Completed
