### ISSUE TITLE
Cannon Mountain Image Map

### ISSUE THREAD

**Issue by JasonD94** [JasonD94/Dynamic-Ski-Maps#14]
Create an image map for the Cannon Mountain page.

Use [this image](http://downing.io/Ski-Maps/img/maps_imgs/cannon_mt.jpg) in GIMP.
[Tutorial on Image Maps.](https://docs.gimp.org/en/plug-in-imagemap.html)

You may want to crop the image before making the map. I would suggest removing the border on the bottom, the left info area, and cutting the top if possible.

**Comment by BrendanBousquet** [comment]
Completed
